const universityData = {
    items: [
        { id: 1, name: "华北水利水电大学", py: "huabeishuilishuidiandaxue", pyi: "hbslsddx", url: "https://www.ncwu.edu.cn/", location: "郑州市", type: "本科" },
        { id: 2, name: "郑州大学", py: "zhengzhoudaxue", pyi: "zzdx", url: "https://www.zzu.edu.cn/", location: "郑州市", type: "本科" },
        { id: 3, name: "河南理工大学", py: "henanligongdaxue", pyi: "hnlgdx", url: "https://www.hpu.edu.cn/", location: "焦作市", type: "本科" },
        { id: 4, name: "郑州轻工业大学", py: "zhengzhouqinggongyedaxue", pyi: "zzqgydx", url: "https://www.zzuli.edu.cn/", location: "郑州市", type: "本科" },
        { id: 5, name: "河南工业大学", py: "henangongyedaxue", pyi: "hngydx", url: "https://www.haut.edu.cn/", location: "郑州市", type: "本科" },
        { id: 6, name: "河南科技大学", py: "henankejidaxue", pyi: "hnkjdx", url: "https://www.haust.edu.cn/", location: "洛阳市", type: "本科" },
        { id: 7, name: "中原工学院", py: "zhongyuangongxueyuan", pyi: "zygxy", url: "https://www.zut.edu.cn/", location: "郑州市", type: "本科" },
        { id: 8, name: "河南农业大学", py: "henannongyedaxue", pyi: "hnnydx", url: "https://www.henau.edu.cn/", location: "郑州市", type: "本科" },
        { id: 9, name: "河南科技学院", py: "henankejixueyuan", pyi: "hnkjxy", url: "https://www.hist.edu.cn/", location: "新乡市", type: "本科" },
        { id: 10, name: "河南牧业经济学院", py: "henanmuyejingjixueyuan", pyi: "hnmyjjxy", url: "https://www.hnuahe.edu.cn/", location: "郑州市", type: "本科" },
        { id: 11, name: "河南中医药大学", py: "henanzhongyiyaodaxue", pyi: "hnzyydx", url: "https://www.hactcm.edu.cn/", location: "郑州市", type: "本科" },
        { id: 12, name: "河南医药大学", py: "henanyiyaoxueyuan", pyi: "hnyydx", url: "https://www.xxmu.edu.cn/", location: "新乡市", type: "本科" },
        { id: 13, name: "河南大学", py: "henandaxue", pyi: "hndx", url: "https://www.henu.edu.cn/", location: "开封市", type: "本科" },
        { id: 14, name: "河南师范大学", py: "henanshifandaxue", pyi: "hnsfdx", url: "https://www.htu.edu.cn/", location: "新乡市", type: "本科" },
        { id: 15, name: "信阳师范大学", py: "xinyangshifandaxue", pyi: "xysfdx", url: "https://www.xynu.edu.cn/", location: "信阳市", type: "本科" },
        { id: 16, name: "周口师范学院", py: "zhoukoushifanxueyuan", pyi: "zksfxy", url: "https://www.zknu.edu.cn/", location: "周口市", type: "本科" },
        { id: 17, name: "安阳师范学院", py: "anyangshifanxueyuan", pyi: "aysfxy", url: "https://www.aynu.edu.cn/", location: "安阳市", type: "本科" },
        { id: 18, name: "许昌学院", py: "xuchangxueyuan", pyi: "xcxy", url: "https://www.xcu.edu.cn/", location: "许昌市", type: "本科" },
        { id: 19, name: "南阳师范学院", py: "nanyangshifanxueyuan", pyi: "nysfxy", url: "https://www.nynu.edu.cn/", location: "南阳市", type: "本科" },
        { id: 20, name: "洛阳师范学院", py: "luoyangshifanxueyuan", pyi: "lysfxy", url: "https://www.lynu.edu.cn/", location: "洛阳市", type: "本科" },
        { id: 21, name: "商丘师范学院", py: "shangqiushifanxueyuan", pyi: "sqsfxy", url: "https://www.sqnu.edu.cn/", location: "商丘市", type: "本科" },
        { id: 22, name: "河南财经政法大学", py: "henancaijingzhengfadaxue", pyi: "hncjzfdx", url: "https://www.huel.edu.cn/", location: "郑州市", type: "本科" },
        { id: 23, name: "郑州航空工业管理学院", py: "zhengzhouhangkonggongyeguanlixueyuan", pyi: "zzhkgyglxy", url: "https://www.zua.edu.cn/", location: "郑州市", type: "本科" },
        { id: 24, name: "黄淮学院", py: "huanghuaixueyuan", pyi: "hhxy", url: "https://www.huanghuai.edu.cn/", location: "驻马店市", type: "本科" },
        { id: 25, name: "平顶山学院", py: "pingdingshanxueyuan", pyi: "pdsxy", url: "https://www.pdsu.edu.cn/", location: "平顶山市", type: "本科" },
        { id: 26, name: "郑州工程技术学院", py: "zhengzhougongchengjishuxueyuan", pyi: "zzgcjsxy", url: "https://www.zzut.edu.cn/", location: "郑州市", type: "本科" },
        { id: 27, name: "洛阳理工学院", py: "luoyangligongxueyuan", pyi: "lylgxy", url: "https://www.lit.edu.cn/", location: "洛阳市", type: "本科" },
        { id: 28, name: "新乡学院", py: "xinxiangxueyuan", pyi: "xxxy", url: "https://www.xxu.edu.cn/", location: "新乡市", type: "本科" },
        { id: 29, name: "信阳农林学院", py: "xinyangnonglinxueyuan", pyi: "xynlxy", url: "https://www.xyafu.edu.cn/", location: "信阳市", type: "本科" },
        { id: 30, name: "河南工学院", py: "henangongxueyuan", pyi: "hngxy", url: "https://www.hait.edu.cn/", location: "新乡市", type: "本科" },
        { id: 31, name: "安阳工学院", py: "anyanggongxueyuan", pyi: "aygxy", url: "https://www.ayit.edu.cn/", location: "安阳市", type: "本科" },
        { id: 32, name: "河南工程学院", py: "henangongchengxueyuan", pyi: "hngcxy", url: "https://www.haue.edu.cn/", location: "郑州市", type: "本科" },
        { id: 33, name: "河南财政金融学院", py: "henancaizhengjinrongxueyuan", pyi: "hnczjrxy", url: "https://www.hafu.edu.cn/", location: "郑州市", type: "本科" },
        { id: 34, name: "南阳理工学院", py: "nanyangligongxueyuan", pyi: "nylgxy", url: "https://www.nyist.edu.cn/", location: "南阳市", type: "本科" },
        { id: 35, name: "河南城建学院", py: "henanchengjianxueyuan", pyi: "hncjxy", url: "https://www.huuc.edu.cn/", location: "平顶山市", type: "本科" },
        { id: 36, name: "河南警察学院", py: "henanjingchaxueyuan", pyi: "hnjcxy", url: "https://www.hnp.edu.cn/", location: "郑州市", type: "本科" },
        { id: 37, name: "黄河科技学院", py: "huanghekejixueyuan", pyi: "hhkjxy", url: "https://www.hhstu.edu.cn/", location: "郑州市", type: "本科" },
        { id: 38, name: "郑州警察学院", py: "zhengzhoujingchaxueyuan", pyi: "zzjcxy", url: "https://www.rpc.edu.cn/", location: "郑州市", type: "本科" },
        { id: 39, name: "郑州科技学院", py: "zhengzhoukejixueyuan", pyi: "zzkjxy", url: "https://www.zit.edu.cn/", location: "郑州市", type: "本科" },
        { id: 40, name: "郑州工业应用技术学院", py: "zhengzhougongyeyingyongjishuxueyuan", pyi: "zzgyyyjsxy", url: "https://www.zzuit.edu.cn/", location: "郑州市", type: "本科" },
        { id: 41, name: "郑州师范学院", py: "zhengzhoushifanxueyuan", pyi: "zzsfxy", url: "https://www.zznu.edu.cn/", location: "郑州市", type: "本科" },
        { id: 42, name: "郑州财经学院", py: "zhengzhoucaijingxueyuan", pyi: "zzcjxy", url: "https://www.zzife.edu.cn/", location: "郑州市", type: "本科" },
        { id: 43, name: "黄河交通学院", py: "huanghejiaotongxueyuan", pyi: "hhjtxy", url: "https://www.zjtu.edu.cn/", location: "焦作市", type: "本科" },
        { id: 44, name: "商丘工学院", py: "shangqiugongxueyuan", pyi: "sqgxy", url: "https://www.sqgxy.edu.cn/", location: "商丘市", type: "本科" },
        { id: 45, name: "河南开封科技传媒学院", py: "henankaifengkejichuanmeixueyuan", pyi: "hnkfkjcmxy", url: "https://www.humc.edu.cn/", location: "开封市", type: "本科" },
        { id: 46, name: "中原科技学院", py: "zhongyuankejixueyuan", pyi: "zykjxy", url: "https://www.zykj.edu.cn/", location: "郑州市", type: "本科" },
        { id: 47, name: "信阳学院", py: "xinyangxueyuan", pyi: "xyxy", url: "https://www.xyu.edu.cn/", location: "信阳市", type: "本科" },
        { id: 48, name: "安阳学院", py: "anyangxueyuan", pyi: "ayxy", url: "https://www.ayxy.edu.cn/", location: "安阳市", type: "本科" },
        { id: 49, name: "豫北医学院", py: "yubeiyixueyuan", pyi: "ybyxy", url: "https://www.nhmu.edu.cn/", location: "新乡市", type: "本科" },
        { id: 50, name: "新乡工程学院", py: "xinxianggongchengxueyuan", pyi: "xxgcxy", url: "https://www.xxgc.edu.cn/", location: "新乡市", type: "本科" },
        { id: 51, name: "郑州工商学院", py: "zhengzhoushanggongxueyuan", pyi: "zzsgxy", url: "https://www.ztbu.edu.cn/", location: "郑州市", type: "本科" },
        { id: 52, name: "郑州经贸学院", py: "zhengzhoujingmaoxueyuan", pyi: "zzjmxy", url: "https://www.zueb.edu.cn/", location: "郑州市", type: "本科" },
        { id: 53, name: "商丘学院", py: "shangqiuxueyuan", pyi: "sqxy", url: "https://www.sqxy.edu.cn/", location: "商丘市", type: "本科" },
        { id: 54, name: "郑州商学院", py: "zhengzhoushangxueyuan", pyi: "zzsxy", url: "https://www.zbu.edu.cn/", location: "郑州市", type: "本科" },
        { id: 55, name: "河南科技职业大学", py: "henankejizhiyedaxue", pyi: "hnkjzydx", url: "https://www.hnvust.cn/", location: "周口市", type: "本科" },
        { id: 56, name: "郑州升达经贸管理学院", py: "zhengzhoushengdajingmaoguanlixueyuan", pyi: "zzsdjmglxy", url: "https://www.shengda.edu.cn/", location: "郑州市", type: "本科" },
        { id: 57, name: "郑州西亚斯学院", py: "zhengzhouxiyasixueyuan", pyi: "zzzysxy", url: "https://www.sias.edu.cn/", location: "郑州市", type: "本科", schoolType: "中外合作" },
        { id: 58, name: "郑州美术学院", py: "zhengzhoumeishuxueyuan", pyi: "zzmsxy", url: "https://www.zzafa.edu.cn/", location: "郑州市", type: "本科" },
        { id: 59, name: "漯河食品工程职业大学", py: "luoheshipingongchengzhiyedaxue", pyi: "lhspgczydx", url: "https://www.lsgx.com.cn/", location: "漯河市", type: "本科" },
        { id: 60, name: "河南体育学院", py: "henantiyuxueyuan", pyi: "hntyxy", url: "https://www.hasu.edu.cn/", location: "郑州市", type: "本科" },
        { id: 61, name: "郑州健康学院", py: "zhengzhoujiankangxueyuan", pyi: "zzjkxy", url: "https://www.zzsqmc.edu.cn/", location: "郑州市", type: "本科" },
        { id: 62, name: "黄河水利职业技术大学", py: "huangheshuilizhiyejishudaxue", pyi: "hhslzyjsdx", url: "https://www.yrcti.edu.cn/", location: "开封市", type: "本科" },
        { id: 63, name: "河南职业技术学院", py: "henanzhiyexueyuan", pyi: "hnzyxy", url: "https://hnzj.edu.cn/", location: "郑州市", type: "专科" },
        { id: 64, name: "漯河职业技术学院", py: "luohezhiyexueyuan", pyi: "lhzyxy", url: "https://www.lhvtc.edu.cn/", location: "漯河市", type: "专科" },
        { id: 65, name: "三门峡职业技术学院", py: "sanmenxiazhiyexueyuan", pyi: "smxzyxy", url: "https://www.smxpt.edu.cn/", location: "三门峡市", type: "专科" },
        { id: 66, name: "郑州铁路职业技术大学", py: "zhengzhoutieluzhiyejishudaxue", pyi: "zztlzyjsdx", url: "https://www.zzrvtc.edu.cn/", location: "郑州市", type: "本科" },
        { id: 67, name: "开封大学", py: "kaifengdaxue", pyi: "kfdx", url: "https://www.kfu.edu.cn/", location: "开封市", type: "专科" },
        { id: 68, name: "焦作大学", py: "jiaozuodaxue", pyi: "jzdx", url: "https://www.jzu.edu.cn/", location: "焦作市", type: "专科" },
        { id: 69, name: "濮阳职业技术学院", py: "puyangzhiyexueyuan", pyi: "pyzyxy", url: "https://www.pyvtc.edu.cn/", location: "濮阳市", type: "专科" },
        { id: 70, name: "郑州电力高等专科学校", py: "zhengzhoudianligaozhengzhuankexuexiao", pyi: "zzdlgzzkxx", url: "https://www.zepc.edu.cn/", location: "郑州市", type: "专科" },
        { id: 71, name: "许昌职业技术学院", py: "xuchangzhiyexueyuan", pyi: "xczyxy", url: "https://www.xcitc.edu.cn/", location: "许昌市", type: "专科" },
        { id: 72, name: "河南工业和信息化职业学院", py: "henangongyeheinxihuazhiyexueyuan", pyi: "hngxhxxzyxy", url: "https://www.hciit.edu.cn/", location: "焦作市", type: "专科" },
        { id: 73, name: "河南水利与环境职业学院", py: "henanshuiliyuhuanjingzhiyexueyuan", pyi: "hnslyhjzyxy", url: "https://www.hwec.edu.cn/", location: "郑州市", type: "专科" },
        { id: 74, name: "商丘职业技术学院", py: "shangqiuzhiyexueyuan", pyi: "sqzyxy", url: "https://www.sqzy.edu.cn/", location: "商丘市", type: "专科" },
        { id: 75, name: "平顶山工业职业技术学院", py: "pingdingshangongyezhiyejishuxueyuan", pyi: "pdsgyzyjsxy", url: "https://www.pzxy.edu.cn/", location: "平顶山市", type: "专科" },
        { id: 76, name: "周口职业技术学院", py: "zhoukouzhiyexueyuan", pyi: "zkzyxy", url: "https://www.zkvtc.edu.cn/", location: "周口市", type: "专科" },
        { id: 77, name: "济源职业技术学院", py: "jiyuanzhiyexueyuan", pyi: "jyzyxy", url: "https://www.jyvtc.edu.cn/", location: "济源市", type: "专科" },
        { id: 78, name: "河南司法警官职业学院", py: "henansifajingguanzhiyexueyuan", pyi: "hnsfjgzyxy", url: "https://www.hnsfjy.edu.cn/", location: "郑州市", type: "专科" },
        { id: 79, name: "鹤壁职业技术学院", py: "hebizhiyexueyuan", pyi: "hbzyxy", url: "https://www.hbzy.edu.cn/", location: "鹤壁市", type: "专科" },
        { id: 80, name: "河南工业职业技术学院", py: "henangongyezhiyejishuxueyuan", pyi: "hngyzyjsxy", url: "https://www.hnpi.edu.cn/", location: "南阳市", type: "专科" },
        { id: 81, name: "焦作师范高等专科学校", py: "jiaozuoshifangaodengzhuankexuexiao", pyi: "jzszgzzkxx", url: "https://www.jzsz.edu.cn/", location: "焦作市", type: "专科" },
        { id: 82, name: "河南检察职业学院", py: "henanjianchazhiyexueyuan", pyi: "hnjczyxy", url: "https://www.hnjc.edu.cn/", location: "郑州市", type: "专科" },
        { id: 83, name: "河南质量工程职业学院", py: "henanzhilianggongchengzhiyexueyuan", pyi: "hnzlgczyxy", url: "https://www.zlxy.edu.cn/", location: "平顶山市", type: "专科" },
        { id: 84, name: "郑州信息科技职业学院", py: "zhengzhouxinxikejizhiyexueyuan", pyi: "zzxxkjzyxy", url: "https://www.techcollege.cn/", location: "郑州市", type: "专科" },
        { id: 85, name: "漯河医学高等专科学校", py: "luoheyixuegaozhengzhuankexuexiao", pyi: "lhyxgzzkxx", url: "https://www.lhmc.edu.cn/", location: "漯河市", type: "专科" },
        { id: 86, name: "南阳医学高等专科学校", py: "nanyangyixuegaozhengzhuankexuexiao", pyi: "nyyxgzzkxx", url: "https://www.nymc.edu.cn/", location: "南阳市", type: "专科" },
        { id: 87, name: "商丘医学高等专科学校", py: "shangqiuyixuegaozhengzhuankexuexiao", pyi: "sqyxgzzkxx", url: "https://www.sqyx.edu.cn/", location: "商丘市", type: "专科" },
        { id: 88, name: "郑州电子信息职业技术学院", py: "zhengzhoudianzixinxizhiyejishuxueyuan", pyi: "zzdzxxzyjsxy", url: "https://www.zyfb.com/", location: "郑州市", type: "专科" },
        { id: 89, name: "信阳职业技术学院", py: "xinyangzhiyexueyuan", pyi: "xyzyxy", url: "https://www.xyvtc.edu.cn/", location: "信阳市", type: "专科" },
        { id: 90, name: "嵩山少林武术职业学院", py: "songshanshaolinwushuzhiyexueyuan", pyi: "ssslwszyxy", url: "https://www.shaolinkungfu.edu.cn/", location: "郑州市", type: "专科" },
        { id: 91, name: "郑州工业安全职业学院", py: "zhengzhougongyeanquanzhiyexueyuan", pyi: "zzgyaqzyxy", url: "https://www.zazy.cn/", location: "郑州市", type: "专科" },
        { id: 92, name: "永城职业学院", py: "yongchengzhiyexueyuan", pyi: "yczyxy", url: "https://www.ycvc.edu.cn/", location: "商丘市", type: "专科" },
        { id: 93, name: "河南经贸职业学院", py: "henanjingmaozhiyexueyuan", pyi: "hnjmzyxy", url: "https://www.henetc.edu.cn/", location: "郑州市", type: "专科" },
        { id: 94, name: "河南交通职业技术学院", py: "henanjiaotongzhiyejishuxueyuan", pyi: "hnjtxxjsxy", url: "https://www.hncc.edu.cn/", location: "郑州市", type: "专科" },
        { id: 95, name: "河南农业职业学院", py: "henannongyezhiyexueyuan", pyi: "hnnyzyxy", url: "https://www.hnca.edu.cn/", location: "郑州市", type: "专科" },
        { id: 96, name: "郑州旅游职业学院", py: "zhengzhoulvyouzhiyexueyuan", pyi: "zzlyzyxy", url: "https://www.zztrc.edu.cn/", location: "郑州市", type: "专科" },
        { id: 97, name: "郑州职业技术学院", py: "zhengzhouzhiyejishuxueyuan", pyi: "zzzyjsxy", url: "https://www.zzyedu.cn/", location: "郑州市", type: "专科" },
        { id: 98, name: "河南信息统计职业学院", py: "henanxinxitongjizhiyexueyuan", pyi: "hnxxtjzyxy", url: "https://www.hnisvc.com/", location: "郑州市", type: "专科" },
        { id: 99, name: "河南林业职业学院", py: "henanlinyezhiyexueyuan", pyi: "hnlyzyxy", url: "https://www.hnfvc.edu.cn/", location: "洛阳市", type: "专科" },
        { id: 100, name: "河南工业贸易职业学院", py: "henangongyemaoyizhiyexueyuan", pyi: "hngymyzyxy", url: "https://www.hngm.edu.cn/", location: "郑州市", type: "专科" },
        { id: 101, name: "郑州电力职业技术学院", py: "zhengzhoudianlizhiyejishuxueyuan", pyi: "zzdlzyjsxy", url: "https://www.zzdl.edu.cn/", location: "郑州市", type: "专科" },
        { id: 102, name: "河南建筑职业技术学院", py: "henanjianzhuzhiyejishuxueyuan", pyi: "hnjzzyjsxy", url: "https://www.hnjs.edu.cn/", location: "郑州市", type: "专科" },
        { id: 103, name: "郑州城市职业学院", py: "zhengzhouchengshizhiyexueyuan", pyi: "zzcszyxy", url: "https://www.zcu.edu.cn/", location: "郑州市", type: "专科" },
        { id: 104, name: "安阳职业技术学院", py: "anyangzhiyexueyuan", pyi: "ayzyxy", url: "https://www.ayzy.edu.cn/", location: "安阳市", type: "专科" },
        { id: 105, name: "新乡职业技术学院", py: "xinxiangzhiyexueyuan", pyi: "xxzyxy", url: "https://www.xxvtc.edu.cn/", location: "新乡市", type: "专科" },
        { id: 106, name: "驻马店职业技术学院", py: "zhumadianzhiyejishuxueyuan", pyi: "zmdzyjsxy", url: "https://www.zmdvtc.edu.cn/", location: "驻马店市", type: "专科" },
        { id: 107, name: "焦作工贸职业学院", py: "jiaozuogongmaozhiyexueyuan", pyi: "jzgmzyxy", url: "https://www.jzcit.edu.cn/", location: "焦作市", type: "专科" },
        { id: 108, name: "许昌陶瓷职业学院", py: "xuchangtaocizhiyexueyuan", pyi: "xctczyxy", url: "https://www.xccvc.com/", location: "许昌市", type: "专科" },
        { id: 109, name: "郑州理工职业学院", py: "zhengzhouligongzhiyexueyuan", pyi: "zzlgzyxy", url: "https://www.zzlgxy.net/", location: "郑州市", type: "专科" },
        { id: 110, name: "郑州信息工程职业学院", py: "zhengzhouxinxigongchengzhiyexueyuan", pyi: "zzxxgczyxy", url: "https://www.zxxyedu.com/", location: "郑州市", type: "专科" },
        { id: 111, name: "长垣烹饪职业技术学院", py: "changyuanpengrenzhiyejishuxueyuan", pyi: "cyprenzyjsxy", url: "https://www.cyprxy.edu.cn/", location: "新乡市", type: "专科" },
        { id: 112, name: "开封文化艺术职业学院", py: "kaifengwenhuayishuzhiyexueyuan", pyi: "kfwxyszyxy", url: "https://www.kfwyxy.edu.cn/", location: "开封市", type: "专科" },
        { id: 113, name: "河南应用技术职业学院", py: "henanyingyongjishuzhiyexueyuan", pyi: "hnyyjszyxy", url: "https://www.hati.edu.cn/", location: "郑州市", type: "专科" },
        { id: 114, name: "河南艺术职业学院", py: "henanyishuzhiyexueyuan", pyi: "hnyszyxy", url: "https://www.hnys.edu.cn/", location: "郑州市", type: "专科" },
        { id: 115, name: "河南机电职业学院", py: "henanjidizhiyexueyuan", pyi: "hnjdzyxy", url: "https://www.hnjd.edu.cn/", location: "郑州市", type: "专科" },
        { id: 116, name: "河南护理职业学院", py: "henanhulizhiyexueyuan", pyi: "hnhlzyxy", url: "https://www.hnnvc.edu.cn/", location: "安阳市", type: "专科" },
        { id: 117, name: "许昌电气职业学院", py: "xuchangdianqizhiyexueyuan", pyi: "xcdqzyxy", url: "https://www.xcevc.edu.cn/", location: "许昌市", type: "专科" },
        { id: 118, name: "信阳涉外职业技术学院", py: "xinyangshewaizhiyejishuxueyuan", pyi: "xyswzyjsxy", url: "https://www.xyswxy.com/", location: "信阳市", type: "专科" },
        { id: 119, name: "鹤壁汽车工程职业学院", py: "hebiqichegongchengzhiyexueyuan", pyi: "hbqcgczyxy", url: "https://www.hbqcxy.com/", location: "鹤壁市", type: "专科" },
        { id: 120, name: "南阳职业学院", py: "nanyangzhiyexueyuan", pyi: "nyzyxy", url: "https://www.nyvc.edu.cn/", location: "南阳市", type: "专科" },
        { id: 121, name: "郑州商贸旅游职业学院", py: "zhengzhoushangmaolvyouzhiyexueyuan", pyi: "zzsmdlyzyxy", url: "https://zzvcct.com/", location: "郑州市", type: "专科" },
        { id: 122, name: "河南推拿职业学院", py: "henantuinaozhiyexueyuan", pyi: "hntyzyxy", url: "https://www.hltn.edu.cn/", location: "洛阳市", type: "专科" },
        { id: 123, name: "洛阳职业技术学院", py: "luoyangzhiyejishuxueyuan", pyi: "lyzyjsxy", url: "https://www.lypt.edu.cn/", location: "洛阳市", type: "专科" },
        { id: 124, name: "郑州幼儿师范高等专科学校", py: "zhengzhouyouershifangaodengzhuankexuexiao", pyi: "zzyesfgzzkxx", url: "https://www.zyedu.org/", location: "郑州市", type: "专科" },
        { id: 125, name: "安阳幼儿师范高等专科学校", py: "anyangyouershifangaodengzhuankexuexiao", pyi: "ayyesfgzzkxx", url: "https://www.ayyz.edu.cn/", location: "安阳市", type: "专科" },
        { id: 126, name: "郑州黄河护理职业学院", py: "zhengzhouhuanghehulizhiyexueyuan", pyi: "zzhhhlzyxy", url: "https://www.zyrnvc.com/", location: "郑州市", type: "专科" },
        { id: 127, name: "河南医学高等专科学校", py: "henanyixuegaozhengzhuankexuexiao", pyi: "hnyxgzzkxx", url: "https://www.hamc.edu.cn/", location: "郑州市", type: "专科" },
        { id: 128, name: "郑州财税金融职业学院", py: "zhengzhoucaishuijinrongzhiyexueyuan", pyi: "zzcsjrzyxy", url: "https://www.zzcsjr.edu.cn/", location: "郑州市", type: "专科" },
        { id: 129, name: "南阳农业职业学院", py: "nanyangnongyezhiyexueyuan", pyi: "nynyzyxy", url: "https://www.nyca.edu.cn/", location: "南阳市", type: "专科" },
        { id: 130, name: "洛阳科技职业学院", py: "luoyangkejizhiyexueyuan", pyi: "lykjzyxy", url: "https://www.lku.edu.cn/", location: "洛阳市", type: "专科" },
        { id: 131, name: "鹤壁能源化工职业学院", py: "hebinengyuanhuagongzhiyexueyuan", pyi: "hbnyhgzyxy", url: "https://www.hbnyhgzyxy.com/", location: "鹤壁市", type: "专科" },
        { id: 132, name: "平顶山文化艺术职业学院", py: "pingdingshanwenhuayishuzhiyexueyuan", pyi: "pdswxyszyxy", url: "https://www.pvcca.edu.cn/", location: "平顶山市", type: "专科" },
        { id: 133, name: "濮阳医学高等专科学校", py: "puyangyixuegaozhengzhuankexuexiao", pyi: "pyyxgzzkxx", url: "https://www.pymc.edu.cn/", location: "濮阳市", type: "专科" },
        { id: 134, name: "驻马店幼儿师范高等专科学校", py: "zhumadianyouershifangaodengzhuankexuexiao", pyi: "zmdyesfgzzkxx", url: "https://zyz.edu.cn/", location: "驻马店市", type: "专科" },
        { id: 135, name: "三门峡社会管理职业学院", py: "sanmenxiashehuiguanlizhiyexueyuan", pyi: "smxshglzyxy", url: "https://www.smxcsa.edu.cn/", location: "三门峡市", type: "专科" },
        { id: 136, name: "河南轻工职业学院", py: "henanqinggongzhiyexueyuan", pyi: "hnqgzyxy", url: "https://www.havcli.edu.cn/", location: "郑州市", type: "专科" },
        { id: 137, name: "河南测绘职业学院", py: "henancehuizhiyexueyuan", pyi: "hncwzyxy", url: "https://www.hasm.edu.cn/", location: "郑州市", type: "专科" },
        { id: 138, name: "信阳航空职业学院", py: "xinyanghangkongzhiyexueyuan", pyi: "xyhkzyxy", url: "https://www.xyhkxy.com/", location: "信阳市", type: "专科" },
        { id: 139, name: "郑州卫生健康职业学院", py: "zhengzhouweishengjiankangzhiyexueyuan", pyi: "zzwsjkzyxy", url: "https://www.zzhvc.cn/", location: "郑州市", type: "专科" },
        { id: 140, name: "河南物流职业学院", py: "henanwuliuzyxy", pyi: "hnwlzyxy", url: "https://www.hnwlxy.edu.cn/", location: "新乡市", type: "专科" },
        { id: 141, name: "河南地矿职业学院", py: "henandikuangzhiyexueyuan", pyi: "hndkzyxy", url: "https://www.hagmc.edu.cn/", location: "郑州市", type: "专科" },
        { id: 142, name: "郑州亚欧交通职业学院", py: "zhengzhouyaoujiaotongzhiyexueyuan", pyi: "zzyojtzyxy", url: "https://www.zzyaou.edu.cn/", location: "郑州市", type: "专科" },
        { id: 143, name: "河南女子职业学院", py: "henannvzizhiyexueyuan", pyi: "hnzzzyxy", url: "https://www.henz.edu.cn/", location: "新乡市", type: "专科" },
        { id: 144, name: "河南对外经济贸易职业学院", py: "henanduiwaijingjimaoyizhiyexueyuan", pyi: "hndwjjmyzyxy", url: "https://www.hnwmxy.edu.cn/", location: "开封市", type: "专科" },
        { id: 145, name: "濮阳石油化工职业技术学院", py: "puyangshihyouhuagongzhiyejishuxueyuan", pyi: "pyshyhghzyjsxy", url: "https://pypcc.edu.cn/", location: "濮阳市", type: "专科" },
        { id: 146, name: "南阳科技职业学院", py: "nanyangkejizhiyexueyuan", pyi: "nykjzyxy", url: "https://www.nystvc.cn/", location: "南阳市", type: "专科" },
        { id: 147, name: "兰考三农职业学院", py: "lankaosannongzhiyexueyuan", pyi: "lksnzyxy", url: "https://www.lksnzyxy.cn/", location: "开封市", type: "专科" },
        { id: 148, name: "汝州职业技术学院", py: "ruzhouzhiyejishuxueyuan", pyi: "rzzyjsxy", url: "https://www.rzvtc.cn/", location: "平顶山市", type: "专科" },
        { id: 149, name: "林州建筑职业技术学院", py: "linzhoujianzhuzhiyejishuxueyuan", pyi: "lzjzzyjsxy", url: "https://lcat.edu.cn/", location: "安阳市", type: "专科" },
        { id: 150, name: "郑州电子商务职业学院", py: "zhengzhoudianzishangwuzhiyexueyuan", pyi: "zzdzswzyxy", url: "https://www.zzdsxy.cn/", location: "郑州市", type: "专科" },
        { id: 151, name: "郑州轨道工程职业学院", py: "zhengzhouguidaogongchengzhiyexueyuan", pyi: "zzgdgczyxy", url: "https://www.zzure.edu.cn/", location: "郑州市", type: "专科" },
        { id: 152, name: "郑州体育职业学院", py: "zhengzhoutiyuzhiyexueyuan", pyi: "zztyzyxy", url: "https://www.zhengzhoutiyuan.com/", location: "郑州市", type: "专科" },
        { id: 153, name: "洛阳文化旅游职业学院", py: "luoyangwenhualvyouzhiyejishuxueyuan", pyi: "lywhlyzyjsxy", url: "http://www.lyvcct.cn/", location: "洛阳市", type: "专科" },
        { id: 154, name: "周口文理职业学院", py: "zhoukouwenlizhiyexueyuan", pyi: "zkwlzyxy", url: "https://www.zkwl.edu.cn/", location: "周口市", type: "专科" },
        { id: 155, name: "信阳艺术职业学院", py: "xinyangyishuzhiyexueyuan", pyi: "xyyszyxy", url: "https://www.xyvca.edu.cn/", location: "信阳市", type: "专科" },
        { id: 156, name: "郑州城建职业学院", py: "zhengzhouchengjianzhiyexueyuan", pyi: "zzcjzyxy", url: "https://www.zzucvc.edu.cn/", location: "郑州市", type: "专科" },
        { id: 157, name: "郑州医药健康职业学院", py: "zhengzhouyiyaojiankangzhiyexueyuan", pyi: "zzyyjkzyxy", url: "https://www.zzyyzy.edu.cn/", location: "郑州市", type: "专科" },
        { id: 158, name: "平顶山职业技术学院", py: "pingdingshanzhiyejishuxueyuan", pyi: "pdszyjsxy", url: "https://www.pdszy.edu.cn/", location: "平顶山市", type: "专科" },
        { id: 159, name: "南阳工艺美术职业学院", py: "nanyanggongyimeishuzhiyexueyuan", pyi: "nygymszyxy", url: "https://www.nygymy.edu.cn/index.htm", location: "南阳市", type: "专科" },
        { id: 160, name: "濮阳科技职业学院", py: "puyangkejizhiyexueyuan", pyi: "pykjzyxy", url: "http://www.pykjzyxy.com/", location: "濮阳市", type: "专科" },
        { id: 161, name: "商丘幼儿师范高等专科学校", py: "shangqiuyouershifangaodengzhuankexuexiao", pyi: "sqyesfgzzkxx", url: "https://www.sqyz.edu.cn/", location: "商丘市", type: "专科" },
        { id: 162, name: "周口理工职业学院", py: "zhoukouligongzhiyexueyuan", pyi: "zklgzyxy", url: "http://www.zkpvc.edu.cn/", location: "周口市", type: "专科" },
        { id: 163, name: "焦作新材料职业学院", py: "jiaozuoxincailiaozhiyexueyuan", pyi: "jzxczyxy", url: "https://jzxcl.edu.cn/", location: "焦作市", type: "专科" },
        { id: 164, name: "开封职业学院", py: "kaifengzhiyexueyuan", pyi: "kfzyxy", url: "https://www.kfvc.edu.cn/", location: "开封市", type: "专科" },
        { id: 165, name: "洛阳商业职业学院", py: "luoyangshangyezhiyexueyuan", pyi: "lysyzyxy", url: "https://lyvcc.com/", location: "洛阳市", type: "专科" },
        { id: 166, name: "郑州软件职业技术学院", py: "zhengzhouruanjianzhiyejishuxueyuan", pyi: "zzrjzyjsxy", url: "https://www.zzsvtc.edu.cn/", location: "郑州市", type: "专科" },
        { id: 167, name: "郑州智能科技职业学院", py: "zhengzhouzhinengkejizhiyexueyuan", pyi: "zzznkjzyxy", url: "https://www.zzcit.edu.cn/", location: "郑州市", type: "专科" },
        { id: 168, name: "郑州食品工程职业学院", py: "zhengzhoushipingongchengzhiyexueyuan", pyi: "zzspgczyxy", url: "https://www.zzfec.edu.cn/", location: "郑州市", type: "专科" },
        { id: 169, name: "郑州汽车工程职业学院", py: "zhengzhouqichegongchengzhiyexueyuan", pyi: "zzqcgczyxy", url: "https://www.zzvcae.edu.cn/", location: "郑州市", type: "专科" },
        { id: 170, name: "驻马店农业工程职业学院", py: "zhumadiannongyegongchengzhiyexueyuan", pyi: "zmdnygczyxy", url: "http://www.zmdavc.edu.cn/", location: "驻马店市", type: "专科" },
        { id: 171, name: "信阳科技职业学院", py: "xinyangkejizhiyexueyuan", pyi: "xykjzyxy", url: "http://www.xykj.edu.cn/", location: "信阳市", type: "专科" },
        { id: 172, name: "信阳工程职业学院", py: "xinyanggongchengzhiyexueyuan", pyi: "xygczyxy", url: "https://www.xygczyxy.com/", location: "信阳市", type: "专科" },
        { id: 173, name: "周口城市职业学院", py: "zhoukouchengshizhiyexueyuan", pyi: "zkcszyxy", url: "https://www.zkcszyxy.com/", location: "周口市", type: "专科" },
        { id: 174, name: "河南新乡工商职业学院", py: "henanxinxianggongshangzhiyexueyuan", pyi: "hnxxgszyxy", url: "http://www.hnxxgs.edu.cn/", location: "新乡市", type: "专科" },
        { id: 175, name: "开封工程职业学院", py: "kaifenggongchengzhiyexueyuan", pyi: "kfgczyxy", url: "https://www.kfevc.edu.cn/", location: "开封市", type: "专科" },
        { id: 176, name: "开封智慧健康职业学院", py: "kaifengzhihuijiankangzhiyexueyuan", pyi: "kfzhjkzyxy", url: "https://www.kfzhjk.edu.cn/", location: "开封市", type: "专科" },
        { id: 177, name: "周口智慧能源职业学院", py: "zhoukouzhihuinengyuanzhiyexueyuan", pyi: "zkzhnyzyxy", url: "http://www.zkzhny.edu.cn/", location: "周口市", type: "专科" },
        { id: 178, name: "平顶山科技职业学院", py: "pingdingshankejizhiyexueyuan", pyi: "pdskjzyxy", url: "https://www.pdskj.edu.cn/", location: "平顶山市", type: "专科" },
        { id: 179, name: "河南能源化工学院", py: "henannengyuanhuagongxueyuan", pyi: "hnnhyghxy", url: "https://www.pygxy.cn/", location: "濮阳市", type: "本科" },
        { id: 180, name: "河南信息科技学院", py: "henanxinxikejixueyuan", pyi: "hnxxkjxy", url: "https://hbcet.hpu.edu.cn/", location: "鹤壁市", type: "本科" },
        { id: 181, name: "河南国医学院", py: "henanguoyixueyuan", pyi: "hngyxy", url: "https://www.zzjpo.edu.cn/", location: "南阳市", type: "本科" },
        { id: 182, name: "河南应用工程学院", py: "henanyingyonggongchengxueyuan", pyi: "hnyygcxy", url: "https://yy.haust.edu.cn/", location: "三门峡市", type: "本科" }
    ],
    sidebar: universitySidebar,
    filters: universityFilters
};

const govData = {
    items: [
        { id: 1, name: "河南省政府采购网（省本级）", py: "henanshengzhengfucaigouwangshengbenji", pyi: "hnszfcgwsbj", url: "https://zfcg.henan.gov.cn/", location: "省本级", type: "省级", desc: "河南省财政厅主办" },
        { id: 2, name: "郑州市政府采购网", py: "zhengzhoushizhengfucaigouwang", pyi: "zzszfcgw", url: "https://zhengzhou.zfcg.henan.gov.cn/", location: "郑州市", type: "地市级", desc: "郑州市分站" },
        { id: 3, name: "开封市政府采购网", py: "kaifengshizhengfucaigouwang", pyi: "kfszfcgw", url: "https://kaifeng.zfcg.henan.gov.cn/", location: "开封市", type: "地市级", desc: "开封市分站" },
        { id: 4, name: "洛阳市政府采购网", py: "luoyangshizhengfucaigouwang", pyi: "lyszfcgw", url: "https://luoyang.zfcg.henan.gov.cn/", location: "洛阳市", type: "地市级", desc: "洛阳市分站" },
        { id: 5, name: "平顶山市政府采购网", py: "pingdingshanshizhengfucaigouwang", pyi: "pdsszfcgw", url: "https://pingdingshan.zfcg.henan.gov.cn/", location: "平顶山市", type: "地市级", desc: "平顶山市分站" },
        { id: 6, name: "安阳市政府采购网", py: "anyangshizhengfucaigouwang", pyi: "ayszfcgw", url: "https://anyang.zfcg.henan.gov.cn/", location: "安阳市", type: "地市级", desc: "安阳市分站" },
        { id: 7, name: "鹤壁市政府采购网", py: "hebishizhengfucaigouwang", pyi: "hbszfcgw", url: "https://hebi.zfcg.henan.gov.cn/", location: "鹤壁市", type: "地市级", desc: "鹤壁市分站" },
        { id: 8, name: "新乡市政府采购网", py: "xinxiangshizhengfucaigouwang", pyi: "xxszfcgw", url: "https://ccgp-henan.gov.cn/xinxiang", location: "新乡市", type: "地市级", desc: "新乡市分站" },
        { id: 9, name: "焦作市政府采购网", py: "jiaozuoshizhengfucaigouwang", pyi: "jzszfcgw", url: "https://jiaozuo.zfcg.henan.gov.cn/", location: "焦作市", type: "地市级", desc: "焦作市分站" },
        { id: 10, name: "濮阳市政府采购网", py: "puyangshizhengfucaigouwang", pyi: "pyszfcgw", url: "https://puyang.zfcg.henan.gov.cn/", location: "濮阳市", type: "地市级", desc: "濮阳市分站" },
        { id: 11, name: "许昌市政府采购网", py: "xuchangshizhengfucaigouwang", pyi: "xcszfcgw", url: "https://ccgp-henan.gov.cn/xuchang", location: "许昌市", type: "地市级", desc: "许昌市分站" },
        { id: 12, name: "漯河市政府采购网", py: "luoheshizhengfucaigouwang", pyi: "lhszfcgw", url: "https://luohe.zfcg.henan.gov.cn/", location: "漯河市", type: "地市级", desc: "漯河市分站" },
        { id: 13, name: "三门峡市政府采购网", py: "sanmenxiashizhengfucaigouwang", pyi: "smxszfcgw", url: "https://sanmenxia.zfcg.henan.gov.cn/", location: "三门峡市", type: "地市级", desc: "三门峡市分站" },
        { id: 14, name: "南阳市政府采购网", py: "nanyangshizhengfucaigouwang", pyi: "nyszfcgw", url: "https://nanyang.zfcg.henan.gov.cn/", location: "南阳市", type: "地市级", desc: "南阳市分站" },
        { id: 15, name: "商丘市政府采购网", py: "shangqiushizhengfucaigouwang", pyi: "sqszfcgw", url: "https://shangqiu.zfcg.henan.gov.cn/", location: "商丘市", type: "地市级", desc: "商丘市分站" },
        { id: 16, name: "信阳市政府采购网", py: "xinyangshizhengfucaigouwang", pyi: "xyszfcgw", url: "https://xinyang.zfcg.henan.gov.cn/", location: "信阳市", type: "地市级", desc: "信阳市分站" },
        { id: 17, name: "周口市政府采购网", py: "zhoukoushizhengfucaigouwang", pyi: "zkszfcgw", url: "https://zhoukou.zfcg.henan.gov.cn/", location: "周口市", type: "地市级", desc: "周口市分站" },
        { id: 18, name: "驻马店市政府采购网", py: "zhumadianshizhengfucaigouwang", pyi: "zmdszfcgw", url: "https://ccgp-henan.gov.cn/zhumadian", location: "驻马店市", type: "地市级", desc: "驻马店市分站" },
        { id: 19, name: "济源市政府采购网", py: "jiyuanshizhengfucaigouwang", pyi: "jyszfcgw", url: "https://ccgp-henan.gov.cn/jiyuan", location: "济源市", type: "地市级", desc: "济源市分站" }
    ],
    sidebar: govSidebar,
    filters: govFilters
};
