const universityData = {
    items: [
        { id: 1, name: "鍗庡寳姘村埄姘寸數澶у", py: "huabeishuilishuidiandaxue", pyi: "hbslsddx", url: "https://www.ncwu.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 2, name: "閮戝窞澶у", py: "zhengzhoudaxue", pyi: "zzdx", url: "https://www.zzu.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 3, name: "娌冲崡鐞嗗伐澶у", py: "henanligongdaxue", pyi: "hnlgdx", url: "https://www.hpu.edu.cn/", location: "鐒︿綔甯?, type: "鏈" },
        { id: 4, name: "閮戝窞杞诲伐涓氬ぇ瀛?, py: "zhengzhouqinggongyedaxue", pyi: "zzqgydx", url: "https://www.zzuli.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 5, name: "娌冲崡宸ヤ笟澶у", py: "henangongyedaxue", pyi: "hngydx", url: "https://www.haut.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 6, name: "娌冲崡绉戞妧澶у", py: "henankejidaxue", pyi: "hnkjdx", url: "https://www.haust.edu.cn/", location: "娲涢槼甯?, type: "鏈" },
        { id: 7, name: "涓師宸ュ闄?, py: "zhongyuangongxueyuan", pyi: "zygxy", url: "https://www.zut.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 8, name: "娌冲崡鍐滀笟澶у", py: "henannongyedaxue", pyi: "hnnydx", url: "https://www.henau.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 9, name: "娌冲崡绉戞妧瀛﹂櫌", py: "henankejixueyuan", pyi: "hnkjxy", url: "https://www.hist.edu.cn/", location: "鏂颁埂甯?, type: "鏈" },
        { id: 10, name: "娌冲崡鐗т笟缁忔祹瀛﹂櫌", py: "henanmuyejingjixueyuan", pyi: "hnmyjjxy", url: "https://www.hnuahe.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 11, name: "娌冲崡涓尰鑽ぇ瀛?, py: "henanzhongyiyaodaxue", pyi: "hnzyydx", url: "https://www.hactcm.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 12, name: "鏂颁埂鍖诲闄?, py: "xinxiangyixueyuan", pyi: "xxyxy", url: "https://www.xxmu.edu.cn/", location: "鏂颁埂甯?, type: "鏈" },
        { id: 13, name: "娌冲崡澶у", py: "henandaxue", pyi: "hndx", url: "https://www.henu.edu.cn/", location: "寮€灏佸競", type: "鏈" },
        { id: 14, name: "娌冲崡甯堣寖澶у", py: "henanshifandaxue", pyi: "hnsfdx", url: "https://www.htu.edu.cn/", location: "鏂颁埂甯?, type: "鏈" },
        { id: 15, name: "淇￠槼甯堣寖澶у", py: "xinyangshifandaxue", pyi: "xysfdx", url: "https://www.xynu.edu.cn/", location: "淇￠槼甯?, type: "鏈" },
        { id: 16, name: "鍛ㄥ彛甯堣寖瀛﹂櫌", py: "zhoukoushifanxueyuan", pyi: "zksfxy", url: "https://www.zknu.edu.cn/", location: "鍛ㄥ彛甯?, type: "鏈" },
        { id: 17, name: "瀹夐槼甯堣寖瀛﹂櫌", py: "anyangshifanxueyuan", pyi: "aysfxy", url: "https://www.aynu.edu.cn/", location: "瀹夐槼甯?, type: "鏈" },
        { id: 18, name: "璁告槍瀛﹂櫌", py: "xuchangxueyuan", pyi: "xcxy", url: "https://www.xcu.edu.cn/", location: "璁告槍甯?, type: "鏈" },
        { id: 19, name: "鍗楅槼甯堣寖瀛﹂櫌", py: "nanyangshifanxueyuan", pyi: "nysfxy", url: "https://www.nynu.edu.cn/", location: "鍗楅槼甯?, type: "鏈" },
        { id: 20, name: "娲涢槼甯堣寖瀛﹂櫌", py: "luoyangshifanxueyuan", pyi: "lysfxy", url: "https://www.lynu.edu.cn/", location: "娲涢槼甯?, type: "鏈" },
        { id: 21, name: "鍟嗕笜甯堣寖瀛﹂櫌", py: "shangqiushifanxueyuan", pyi: "sqsfxy", url: "https://www.sqnu.edu.cn/", location: "鍟嗕笜甯?, type: "鏈" },
        { id: 22, name: "娌冲崡璐㈢粡鏀挎硶澶у", py: "henancaijingzhengfadaxue", pyi: "hncjzfdx", url: "https://www.huel.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 23, name: "閮戝窞鑸┖宸ヤ笟绠＄悊瀛﹂櫌", py: "zhengzhouhangkonggongyeguanlixueyuan", pyi: "zzhkgyglxy", url: "https://www.zua.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 24, name: "榛勬樊瀛﹂櫌", py: "huanghuaixueyuan", pyi: "hhxy", url: "https://www.huanghuai.edu.cn/", location: "椹婚┈搴楀競", type: "鏈" },
        { id: 25, name: "骞抽《灞卞闄?, py: "pingdingshanxueyuan", pyi: "pdsxy", url: "https://www.pdsu.edu.cn/", location: "骞抽《灞卞競", type: "鏈" },
        { id: 26, name: "閮戝窞宸ョ▼鎶€鏈闄?, py: "zhengzhougongchengjishuxueyuan", pyi: "zzgcjsxy", url: "https://www.zzut.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 27, name: "娲涢槼鐞嗗伐瀛﹂櫌", py: "luoyangligongxueyuan", pyi: "lylgxy", url: "https://www.lit.edu.cn/", location: "娲涢槼甯?, type: "鏈" },
        { id: 28, name: "鏂颁埂瀛﹂櫌", py: "xinxiangxueyuan", pyi: "xxxy", url: "https://www.xxu.edu.cn/", location: "鏂颁埂甯?, type: "鏈" },
        { id: 29, name: "淇￠槼鍐滄灄瀛﹂櫌", py: "xinyangnonglinxueyuan", pyi: "xynlxy", url: "https://www.xyafu.edu.cn/", location: "淇￠槼甯?, type: "鏈" },
        { id: 30, name: "娌冲崡宸ュ闄?, py: "henangongxueyuan", pyi: "hngxy", url: "https://www.hait.edu.cn/", location: "鏂颁埂甯?, type: "鏈" },
        { id: 31, name: "瀹夐槼宸ュ闄?, py: "anyanggongxueyuan", pyi: "aygxy", url: "https://www.ayit.edu.cn/", location: "瀹夐槼甯?, type: "鏈" },
        { id: 32, name: "娌冲崡宸ョ▼瀛﹂櫌", py: "henangongchengxueyuan", pyi: "hngcxy", url: "https://www.haue.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 33, name: "娌冲崡璐㈡斂閲戣瀺瀛﹂櫌", py: "henancaizhengjinrongxueyuan", pyi: "hnczjrxy", url: "https://www.hafu.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 34, name: "鍗楅槼鐞嗗伐瀛﹂櫌", py: "nanyangligongxueyuan", pyi: "nylgxy", url: "https://www.nyist.edu.cn/", location: "鍗楅槼甯?, type: "鏈" },
        { id: 35, name: "娌冲崡鍩庡缓瀛﹂櫌", py: "henanchengjianxueyuan", pyi: "hncjxy", url: "https://www.huuc.edu.cn/", location: "骞抽《灞卞競", type: "鏈" },
        { id: 36, name: "娌冲崡璀﹀療瀛﹂櫌", py: "henanjingchaxueyuan", pyi: "hnjcxy", url: "https://www.hnp.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 37, name: "榛勬渤绉戞妧瀛﹂櫌", py: "huanghekejixueyuan", pyi: "hhkjxy", url: "https://www.hhstu.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 38, name: "閮戝窞璀﹀療瀛﹂櫌", py: "zhengzhoujingchaxueyuan", pyi: "zzjcxy", url: "https://www.rpc.edu.cn", location: "閮戝窞甯?, type: "鏈" },
        { id: 39, name: "閮戝窞绉戞妧瀛﹂櫌", py: "zhengzhoukejixueyuan", pyi: "zzkjxy", url: "https://www.zit.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 40, name: "閮戝窞宸ヤ笟搴旂敤鎶€鏈闄?, py: "zhengzhougongyeyingyongjishuxueyuan", pyi: "zzgyyyjsxy", url: "https://www.zzuit.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 41, name: "閮戝窞甯堣寖瀛﹂櫌", py: "zhengzhoushifanxueyuan", pyi: "zzsfxy", url: "https://www.zznu.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 42, name: "閮戝窞璐㈢粡瀛﹂櫌", py: "zhengzhoucaijingxueyuan", pyi: "zzcjxy", url: "https://www.zzife.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 43, name: "榛勬渤浜ら€氬闄?, py: "huanghejiaotongxueyuan", pyi: "hhjtxy", url: "https://www.zjtu.edu.cn/", location: "鐒︿綔甯?, type: "鏈" },
        { id: 44, name: "鍟嗕笜宸ュ闄?, py: "shangqiugongxueyuan", pyi: "sqgxy", url: "https://www.sqgxy.edu.cn/", location: "鍟嗕笜甯?, type: "鏈" },
        { id: 45, name: "娌冲崡寮€灏佺鎶€浼犲獟瀛﹂櫌", py: "henankaifengkejichuanmeixueyuan", pyi: "hnkfkjcmxy", url: "https://www.humc.edu.cn/", location: "寮€灏佸競", type: "鏈" },
        { id: 46, name: "涓師绉戞妧瀛﹂櫌", py: "zhongyuankejixueyuan", pyi: "zykjxy", url: "https://www.zykj.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 47, name: "淇￠槼瀛﹂櫌", py: "xinyangxueyuan", pyi: "xyxy", url: "https://www.xyu.edu.cn/", location: "淇￠槼甯?, type: "鏈" },
        { id: 48, name: "瀹夐槼瀛﹂櫌", py: "anyangxueyuan", pyi: "ayxy", url: "https://www.ayxy.edu.cn/", location: "瀹夐槼甯?, type: "鏈" },
        { id: 49, name: "璞寳鍖诲闄?, py: "yubeiyixueyuan", pyi: "ybyxy", url: "https://www.nhmu.edu.cn/", location: "鏂颁埂甯?, type: "鏈" },
        { id: 50, name: "鏂颁埂宸ョ▼瀛﹂櫌", py: "xinxianggongchengxueyuan", pyi: "xxgcxy", url: "https://www.xxgc.edu.cn/", location: "鏂颁埂甯?, type: "鏈" },
        { id: 51, name: "閮戝窞宸ュ晢瀛﹂櫌", py: "zhengzhougongshangxueyuan", pyi: "zzgsxy", url: "https://www.ztbu.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 52, name: "閮戝窞缁忚锤瀛﹂櫌", py: "zhengzhoujingmaoxueyuan", pyi: "zzjmxy", url: "https://www.zueb.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 53, name: "鍟嗕笜瀛﹂櫌", py: "shangqiuxueyuan", pyi: "sqxy", url: "https://www.sqxy.edu.cn/", location: "鍟嗕笜甯?, type: "鏈" },
        { id: 54, name: "閮戝窞鍟嗗闄?, py: "zhengzhoushangxueyuan", pyi: "zzsxy", url: "https://www.zbu.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 55, name: "娌冲崡绉戞妧鑱屼笟澶у", py: "henankejizhiyedaxue", pyi: "hnkjzydx", url: "https://www.hnvust.cn/", location: "鍛ㄥ彛甯?, type: "鏈" },
        { id: 56, name: "閮戝窞鍗囪揪缁忚锤绠＄悊瀛﹂櫌", py: "zhengzhoushengdajingmaoguanlixueyuan", pyi: "zzsdjmglxy", url: "https://www.shengda.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 57, name: "閮戝窞瑗夸簹鏂闄?, py: "zhengzhouxiyasixueyuan", pyi: "zzxysxy", url: "https://www.sias.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 58, name: "閮戝窞缇庢湳瀛﹂櫌", py: "zhengzhoumeishuxueyuan", pyi: "zzmsxy", url: "https://www.zzafa.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 59, name: "婕渤椋熷搧宸ョ▼鑱屼笟澶у", py: "luoheshipingongchengzhiyedaxue", pyi: "lhspgczydx", url: "https://www.lsgx.com.cn/", location: "婕渤甯?, type: "鏈" },
        { id: 60, name: "娌冲崡浣撹偛瀛﹂櫌", py: "henantiyuxueyuan", pyi: "hntyxy", url: "https://www.hasu.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 61, name: "閮戝窞鍋ュ悍瀛﹂櫌", py: "zhengzhoujiankangxueyuan", pyi: "zzjkxy", url: "https://www.zzsqmc.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 62, name: "榛勬渤姘村埄鑱屼笟鎶€鏈ぇ瀛?, py: "huangheshuilizhiyejishudaxue", pyi: "hhslzyjsdx", url: "https://www.yrcti.edu.cn/", location: "寮€灏佸競", type: "鏈" },
        { id: 179, name: "娌冲崡鑳芥簮鍖栧伐瀛﹂櫌", py: "henannengyuanhuagongxueyuan", pyi: "hnnyhgxy", url: "https://www.pygxy.cn/", location: "婵槼甯?, type: "鏈" },
        { id: 180, name: "娌冲崡淇℃伅绉戞妧瀛﹂櫌", py: "henanxinxikejixueyuan", pyi: "hnxxkjxy", url: "https://hbcet.hpu.edu.cn/", location: "楣ゅ甯?, type: "鏈" },
        { id: 181, name: "娌冲崡鍥藉尰瀛﹂櫌", py: "henanguoyixueyuan", pyi: "hngyxy", url: "https://www.zzjpo.edu.cn/", location: "鍗楅槼甯?, type: "鏈" },
        { id: 182, name: "娌冲崡搴旂敤宸ョ▼瀛﹂櫌", py: "henanyingyonggongchengxueyuan", pyi: "hnyygcxy", url: "https://yy.haust.edu.cn/", location: "涓夐棬宄″競", type: "鏈" },
        { id: 63, name: "娌冲崡鑱屼笟鎶€鏈闄?, py: "henanzhiyejishuxueyuan", pyi: "hnzyjsxy", url: "https://hnzj.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 64, name: "婕渤鑱屼笟鎶€鏈闄?, py: "luohezhiyejishuxueyuan", pyi: "lhzyjsxy", url: "https://www.lhvtc.edu.cn/", location: "婕渤甯?, type: "涓撶" },
        { id: 65, name: "涓夐棬宄¤亴涓氭妧鏈闄?, py: "sanmenxiazhiyejishuxueyuan", pyi: "smxzyjsxy", url: "https://www.smxpt.edu.cn/", location: "涓夐棬宄″競", type: "涓撶" },
        { id: 66, name: "閮戝窞閾佽矾鑱屼笟鎶€鏈ぇ瀛?, py: "zhengzhoutieluzhiyejishudaxue", pyi: "zztlzyjsdx", url: "https://www.zzrvtc.edu.cn/", location: "閮戝窞甯?, type: "鏈" },
        { id: 67, name: "寮€灏佸ぇ瀛?, py: "kaifengdaxue", pyi: "kfdx", url: "https://www.kfu.edu.cn/", location: "寮€灏佸競", type: "涓撶" },
        { id: 68, name: "鐒︿綔澶у", py: "jiaozuodaxue", pyi: "jzdx", url: "https://www.jzu.edu.cn/", location: "鐒︿綔甯?, type: "涓撶" },
        { id: 69, name: "婵槼鑱屼笟鎶€鏈闄?, py: "puyangzhiyejishuxueyuan", pyi: "pyzyjsxy", url: "https://www.pyvtc.edu.cn/", location: "婵槼甯?, type: "涓撶" },
        { id: 70, name: "閮戝窞鐢靛姏楂樼瓑涓撶瀛︽牎", py: "zhengzhoudianligaodengzhuankexuexiao", pyi: "zzdlgdzkxx", url: "https://www.zepc.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 71, name: "璁告槍鑱屼笟鎶€鏈闄?, py: "xuchangzhiyejishuxueyuan", pyi: "xczyjsxy", url: "https://www.xcitc.edu.cn/", location: "璁告槍甯?, type: "涓撶" },
        { id: 72, name: "娌冲崡宸ヤ笟鍜屼俊鎭寲鑱屼笟瀛﹂櫌", py: "henangongyehexinxihuazhiyexueyuan", pyi: "hngyhxxhzyxy", url: "https://www.hciit.edu.cn/", location: "鐒︿綔甯?, type: "涓撶" },
        { id: 73, name: "娌冲崡姘村埄涓庣幆澧冭亴涓氬闄?, py: "henanshuiliyuhuanjingzhiyexueyuan", pyi: "hnslyhjzyxy", url: "https://www.hwec.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 74, name: "鍟嗕笜鑱屼笟鎶€鏈闄?, py: "shangqiuzhiyejishuxueyuan", pyi: "sqzyjsxy", url: "https://www.sqzy.edu.cn/", location: "鍟嗕笜甯?, type: "涓撶" },
        { id: 75, name: "骞抽《灞卞伐涓氳亴涓氭妧鏈闄?, py: "pingdingshangongyezhiyejishuxueyuan", pyi: "pdsgyzyjsxy", url: "https://www.pzxy.edu.cn/", location: "骞抽《灞卞競", type: "涓撶" },
        { id: 76, name: "鍛ㄥ彛鑱屼笟鎶€鏈闄?, py: "zhoukouzhiyejishuxueyuan", pyi: "zkzyjsxy", url: "https://www.zkvtc.edu.cn/", location: "鍛ㄥ彛甯?, type: "涓撶" },
        { id: 77, name: "娴庢簮鑱屼笟鎶€鏈闄?, py: "jiyuanzhiyejishuxueyuan", pyi: "jyzyjsxy", url: "https://www.jyvtc.edu.cn/", location: "娴庢簮甯?, type: "涓撶" },
        { id: 78, name: "娌冲崡鍙告硶璀﹀畼鑱屼笟瀛﹂櫌", py: "henansifajingguanzhiyexueyuan", pyi: "hnsfjgzyxy", url: "https://www.hnsfjy.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 79, name: "楣ゅ鑱屼笟鎶€鏈闄?, py: "hebizhiyejishuxueyuan", pyi: "hbzyjsxy", url: "https://www.hbzy.edu.cn/", location: "楣ゅ甯?, type: "涓撶" },
        { id: 80, name: "娌冲崡宸ヤ笟鑱屼笟鎶€鏈闄?, py: "henangongyezhiyejishuxueyuan", pyi: "hngyzyjsxy", url: "https://www.hnpi.edu.cn/", location: "鍗楅槼甯?, type: "涓撶" },
        { id: 81, name: "鐒︿綔甯堣寖楂樼瓑涓撶瀛︽牎", py: "jiaozuoshifangaodengzhuankexuexiao", pyi: "jzsfgdzkxx", url: "https://www.jzsz.edu.cn/", location: "鐒︿綔甯?, type: "涓撶" },
        { id: 82, name: "娌冲崡妫€瀵熻亴涓氬闄?, py: "henanjianchazhiyexueyuan", pyi: "hnjczyxy", url: "https://www.hnjc.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 83, name: "娌冲崡璐ㄩ噺宸ョ▼鑱屼笟瀛﹂櫌", py: "henanzhilianggongchengzhiyexueyuan", pyi: "hnzlgczyxy", url: "https://www.zlxy.edu.cn/", location: "骞抽《灞卞競", type: "涓撶" },
        { id: 84, name: "閮戝窞淇℃伅绉戞妧鑱屼笟瀛﹂櫌", py: "zhengzhouxinxikejizhiyexueyuan", pyi: "zzxxkjzyxy", url: "https://www.techcollege.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 85, name: "婕渤鍖诲楂樼瓑涓撶瀛︽牎", py: "luoheyixuegaodengzhuankexuexiao", pyi: "lhyxgdzkxx", url: "https://www.lhmc.edu.cn", location: "婕渤甯?, type: "涓撶" },
        { id: 86, name: "鍗楅槼鍖诲楂樼瓑涓撶瀛︽牎", py: "nanyangyixuegaodengzhuankexuexiao", pyi: "nyyxgdzkxx", url: "https://www.nymc.edu.cn/", location: "鍗楅槼甯?, type: "涓撶" },
        { id: 87, name: "鍟嗕笜鍖诲楂樼瓑涓撶瀛︽牎", py: "shangqiuyixuegaodengzhuankexuexiao", pyi: "sqyxgdzkxx", url: "https://www.sqyx.edu.cn/", location: "鍟嗕笜甯?, type: "涓撶" },
        { id: 88, name: "閮戝窞鐢靛瓙淇℃伅鑱屼笟鎶€鏈闄?, py: "zhengzhoudianzixinxizhiyejishuxueyuan", pyi: "zzdzxxzyjsxy", url: "https://www.zyfb.com/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 89, name: "淇￠槼鑱屼笟鎶€鏈闄?, py: "xinyangzhiyejishuxueyuan", pyi: "xyzyjsxy", url: "https://www.xyvtc.edu.cn/", location: "淇￠槼甯?, type: "涓撶" },
        { id: 90, name: "宓╁北灏戞灄姝︽湳鑱屼笟瀛﹂櫌", py: "songshanshaolinwushuzhiyexueyuan", pyi: "ssslwszyxy", url: "https://www.shaolinkungfu.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 91, name: "閮戝窞宸ヤ笟瀹夊叏鑱屼笟瀛﹂櫌", py: "zhengzhougongyeanquanzhiyexueyuan", pyi: "zzgyaqzyxy", url: "https://www.zazy.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 92, name: "姘稿煄鑱屼笟瀛﹂櫌", py: "yongchengzhiyexueyuan", pyi: "yczyxy", url: "https://www.ycvc.edu.cn/", location: "鍟嗕笜甯?, type: "涓撶" },
        { id: 93, name: "娌冲崡缁忚锤鑱屼笟瀛﹂櫌", py: "henanjingmaozhiyexueyuan", pyi: "hnjmzyxy", url: "https://www.henetc.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 94, name: "娌冲崡浜ら€氳亴涓氭妧鏈闄?, py: "henanjiaotongzhiyejishuxueyuan", pyi: "hnjtzyjsxy", url: "https://www.hncc.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 95, name: "娌冲崡鍐滀笟鑱屼笟瀛﹂櫌", py: "henannongyezhiyexueyuan", pyi: "hnnyzyxy", url: "https://www.hnca.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 96, name: "閮戝窞鏃呮父鑱屼笟瀛﹂櫌", py: "zhengzhoul眉youzhiyexueyuan", pyi: "zzlyzyxy", url: "https://www.zztrc.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 97, name: "閮戝窞鑱屼笟鎶€鏈闄?, py: "zhengzhouzhiyejishuxueyuan", pyi: "zzzyjsxy", url: "https://www.zzyedu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 98, name: "娌冲崡淇℃伅缁熻鑱屼笟瀛﹂櫌", py: "henanxinxitongjizhiyexueyuan", pyi: "hnxxtjzyxy", url: "https://www.hnisvc.com/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 99, name: "娌冲崡鏋椾笟鑱屼笟瀛﹂櫌", py: "henanlinyezhiyexueyuan", pyi: "hnlyzyxy", url: "https://www.hnfvc.edu.cn/", location: "娲涢槼甯?, type: "涓撶" },
        { id: 100, name: "娌冲崡宸ヤ笟璐告槗鑱屼笟瀛﹂櫌", py: "henangongyemaoyizhiyexueyuan", pyi: "hngymyzyxy", url: "https://www.hngm.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 101, name: "閮戝窞鐢靛姏鑱屼笟鎶€鏈闄?, py: "zhengzhoudianlizhiyejishuxueyuan", pyi: "zzdlzyjsxy", url: "https://www.zzdl.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 102, name: "娌冲崡寤虹瓚鑱屼笟鎶€鏈闄?, py: "henanjianzhuzhiyejishuxueyuan", pyi: "hnjzzyjsxy", url: "https://www.hnjs.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 103, name: "閮戝窞鍩庡競鑱屼笟瀛﹂櫌", py: "zhengzhouchengshizhiyexueyuan", pyi: "zzcszyxy", url: "https://www.zcu.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 104, name: "瀹夐槼鑱屼笟鎶€鏈闄?, py: "anyangzhiyejishuxueyuan", pyi: "ayzyjsxy", url: "https://www.ayzy.edu.cn/", location: "瀹夐槼甯?, type: "涓撶" },
        { id: 105, name: "鏂颁埂鑱屼笟鎶€鏈闄?, py: "xinxiangzhiyejishuxueyuan", pyi: "xxzyjsxy", url: "https://www.xxvtc.edu.cn/", location: "鏂颁埂甯?, type: "涓撶" },
        { id: 106, name: "椹婚┈搴楄亴涓氭妧鏈闄?, py: "zhumadianzhiyejishuxueyuan", pyi: "zmdzyjsxy", url: "https://www.zmdvtc.edu.cn/", location: "椹婚┈搴楀競", type: "涓撶" },
        { id: 107, name: "鐒︿綔宸ヨ锤鑱屼笟瀛﹂櫌", py: "jiaozuogongmaozhiyexueyuan", pyi: "jzgmzyxy", url: "https://www.jzcit.edu.cn/", location: "鐒︿綔甯?, type: "涓撶" },
        { id: 108, name: "璁告槍闄剁摲鑱屼笟瀛﹂櫌", py: "xuchangtaocizhiyexueyuan", pyi: "xctczyxy", url: "https://www.xccvc.com/", location: "璁告槍甯?, type: "涓撶" },
        { id: 109, name: "閮戝窞鐞嗗伐鑱屼笟瀛﹂櫌", py: "zhengzhouligongzhiyexueyuan", pyi: "zzlgzyxy", url: "https://www.zzlgxy.net/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 110, name: "閮戝窞淇℃伅宸ョ▼鑱屼笟瀛﹂櫌", py: "zhengzhouxinxigongchengzhiyexueyuan", pyi: "zzxxgczyxy", url: "https://www.zxxyedu.com/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 111, name: "闀垮灒鐑归オ鑱屼笟鎶€鏈闄?, py: "changyuanpengrenzhiyejishuxueyuan", pyi: "cyprzyjsxy", url: "https://www.cyprxy.edu.cn/", location: "鏂颁埂甯?, type: "涓撶" },
        { id: 112, name: "寮€灏佹枃鍖栬壓鏈亴涓氬闄?, py: "kaifengwenhuayishuzhiyexueyuan", pyi: "kfwhyszyxy", url: "https://www.kfwyxy.edu.cn/", location: "寮€灏佸競", type: "涓撶" },
        { id: 113, name: "娌冲崡搴旂敤鎶€鏈亴涓氬闄?, py: "henanyingyongjishuzhiyexueyuan", pyi: "hnyyjszyxy", url: "https://www.hati.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 114, name: "娌冲崡鑹烘湳鑱屼笟瀛﹂櫌", py: "henanyishuzhiyexueyuan", pyi: "hnyszyxy", url: "https://www.hnys.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 115, name: "娌冲崡鏈虹數鑱屼笟瀛﹂櫌", py: "henanjidianzhiyexueyuan", pyi: "hnjdzyxy", url: "https://www.hnjd.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 116, name: "娌冲崡鎶ょ悊鑱屼笟瀛﹂櫌", py: "henanhulizhiyexueyuan", pyi: "hnhlzyxy", url: "https://www.hnnvc.edu.cn/", location: "瀹夐槼甯?, type: "涓撶" },
        { id: 117, name: "璁告槍鐢垫皵鑱屼笟瀛﹂櫌", py: "xuchangdianqizhiyexueyuan", pyi: "xcdqzyxy", url: "https://www.xcevc.edu.cn/", location: "璁告槍甯?, type: "涓撶" },
        { id: 118, name: "淇￠槼娑夊鑱屼笟鎶€鏈闄?, py: "xinyangshewaizhiyejishuxueyuan", pyi: "xyswzyjsxy", url: "https://www.xyswxy.com/", location: "淇￠槼甯?, type: "涓撶" },
        { id: 119, name: "楣ゅ姹借溅宸ョ▼鑱屼笟瀛﹂櫌", py: "hebiqichegongchengzhiyexueyuan", pyi: "hbqcgczyxy", url: "https://www.hbqcxy.com/", location: "楣ゅ甯?, type: "涓撶" },
        { id: 120, name: "鍗楅槼鑱屼笟瀛﹂櫌", py: "nanyangzhiyexueyuan", pyi: "nyzyxy", url: "https://www.nyvc.edu.cn/", location: "鍗楅槼甯?, type: "涓撶" },
        { id: 121, name: "閮戝窞鍟嗚锤鏃呮父鑱屼笟瀛﹂櫌", py: "zhengzhoushangmaol眉youzhiyexueyuan", pyi: "zzsmlyzyxy", url: "https://zzvcct.com/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 122, name: "娌冲崡鎺ㄦ嬁鑱屼笟瀛﹂櫌", py: "henantuinazhiyexueyuan", pyi: "hntnzyxy", url: "https://www.hltn.edu.cn/index.htm", location: "娲涢槼甯?, type: "涓撶" },
        { id: 123, name: "娲涢槼鑱屼笟鎶€鏈闄?, py: "luoyangzhiyejishuxueyuan", pyi: "lyzyjsxy", url: "https://www.lypt.edu.cn/", location: "娲涢槼甯?, type: "涓撶" },
        { id: 124, name: "閮戝窞骞煎効甯堣寖楂樼瓑涓撶瀛︽牎", py: "zhengzhouyouershifangaodengzhuankexuexiao", pyi: "zzyesfgdzkxx", url: "https://www.zyedu.org/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 125, name: "瀹夐槼骞煎効甯堣寖楂樼瓑涓撶瀛︽牎", py: "anyangyouershifangaodengzhuankexuexiao", pyi: "ayyesfgdzkxx", url: "https://www.ayyz.edu.cn/", location: "瀹夐槼甯?, type: "涓撶" },
        { id: 126, name: "閮戝窞榛勬渤鎶ょ悊鑱屼笟瀛﹂櫌", py: "zhengzhouhuanghehulizhiyexueyuan", pyi: "zzhhhlzyxy", url: "https://www.zyrnvc.com/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 127, name: "娌冲崡鍖诲楂樼瓑涓撶瀛︽牎", py: "henanyixuegaodengzhuankexuexiao", pyi: "hnyxgdzkxx", url: "https://www.hamc.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 128, name: "閮戝窞璐㈢◣閲戣瀺鑱屼笟瀛﹂櫌", py: "zhengzhoucaishuijinrongzhiyexueyuan", pyi: "zzcsjrzyxy", url: "https://www.zzcsjr.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 129, name: "鍗楅槼鍐滀笟鑱屼笟瀛﹂櫌", py: "nanyangnongyezhiyexueyuan", pyi: "nynyzyxy", url: "https://www.nyca.edu.cn/", location: "鍗楅槼甯?, type: "涓撶" },
        { id: 130, name: "娲涢槼绉戞妧鑱屼笟瀛﹂櫌", py: "luoyangkejizhiyexueyuan", pyi: "lykjzyxy", url: "https://www.lku.edu.cn/", location: "娲涢槼甯?, type: "涓撶" },
        { id: 131, name: "楣ゅ鑳芥簮鍖栧伐鑱屼笟瀛﹂櫌", py: "hebinengyuanhuagongzhiyexueyuan", pyi: "hbnyhgzyxy", url: "https://www.hbnyhgzyxy.com/", location: "楣ゅ甯?, type: "涓撶" },
        { id: 132, name: "骞抽《灞辨枃鍖栬壓鏈亴涓氬闄?, py: "pingdingshanwenhuayishuzhiyexueyuan", pyi: "pdswhyszyxy", url: "https://www.pvcca.edu.cn/", location: "骞抽《灞卞競", type: "涓撶" },
        { id: 133, name: "婵槼鍖诲楂樼瓑涓撶瀛︽牎", py: "puyangyixuegaodengzhuankexuexiao", pyi: "pyyxgdzkxx", url: "https://www.pymc.edu.cn/index.htm", location: "婵槼甯?, type: "涓撶" },
        { id: 134, name: "椹婚┈搴楀辜鍎垮笀鑼冮珮绛変笓绉戝鏍?, py: "zhumadianyouershifangaodengzhuankexuexiao", pyi: "zmdyesfgdzkxx", url: "https://zyz.edu.cn/", location: "椹婚┈搴楀競", type: "涓撶" },
        { id: 135, name: "涓夐棬宄＄ぞ浼氱鐞嗚亴涓氬闄?, py: "sanmenxiashehuiguanlizhiyexueyuan", pyi: "smxshglzyxy", url: "https://www.smxcsa.edu.cn/", location: "涓夐棬宄″競", type: "涓撶" },
        { id: 136, name: "娌冲崡杞诲伐鑱屼笟瀛﹂櫌", py: "henanqinggongzhiyexueyuan", pyi: "hnqgzyxy", url: "https://www.havcli.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 137, name: "娌冲崡娴嬬粯鑱屼笟瀛﹂櫌", py: "henancehuizhiyexueyuan", pyi: "hnchzyxy", url: "https://www.hasm.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 138, name: "淇￠槼鑸┖鑱屼笟瀛﹂櫌", py: "xinyanghangkongzhiyexueyuan", pyi: "xyhkzyxy", url: "https://www.xyhkxy.com/", location: "淇￠槼甯?, type: "涓撶" },
        { id: 139, name: "閮戝窞鍗敓鍋ュ悍鑱屼笟瀛﹂櫌", py: "zhengzhouweishengjiankangzhiyexueyuan", pyi: "zzwsjkzyxy", url: "https://www.zzhvc.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 140, name: "娌冲崡鐗╂祦鑱屼笟瀛﹂櫌", py: "henanwuliuzhiyexueyuan", pyi: "hnwlzyxy", url: "https://www.hnwlxy.edu.cn/index.htm", location: "鏂颁埂甯?, type: "涓撶" },
        { id: 141, name: "娌冲崡鍦扮熆鑱屼笟瀛﹂櫌", py: "henandikuangzhiyexueyuan", pyi: "hndkzyxy", url: "https://www.hagmc.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 142, name: "閮戝窞浜氭浜ら€氳亴涓氬闄?, py: "zhengzhouyaoujiaotongzhiyexueyuan", pyi: "zzyojtzyxy", url: "https://www.zzyaou.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 143, name: "娌冲崡濂冲瓙鑱屼笟瀛﹂櫌", py: "henann眉zizhiyexueyuan", pyi: "hnnzzyxy", url: "https://www.henz.edu.cn/", location: "鏂颁埂甯?, type: "涓撶" },
        { id: 144, name: "娌冲崡瀵瑰缁忔祹璐告槗鑱屼笟瀛﹂櫌", py: "henanduiwaijingjimaoyizhiyexueyuan", pyi: "hndwjjmyzyxy", url: "https://www.hnwmxy.edu.cn/", location: "寮€灏佸競", type: "涓撶" },
        { id: 145, name: "婵槼鐭虫补鍖栧伐鑱屼笟鎶€鏈闄?, py: "puyangshiyouhuagongzhiyejishuxueyuan", pyi: "pysyhgzyjsxy", url: "https://pypcc.edu.cn/", location: "婵槼甯?, type: "涓撶" },
        { id: 146, name: "鍗楅槼绉戞妧鑱屼笟瀛﹂櫌", py: "nanyangkejizhiyexueyuan", pyi: "nykjzyxy", url: "https://www.nystvc.cn/", location: "鍗楅槼甯?, type: "涓撶" },
        { id: 147, name: "鍏拌€冧笁鍐滆亴涓氬闄?, py: "lankaosannongzhiyexueyuan", pyi: "lksnzyxy", url: "https://www.lksnzyxy.cn/", location: "寮€灏佸競", type: "涓撶" },
        { id: 148, name: "姹濆窞鑱屼笟鎶€鏈闄?, py: "ruzhouzhiyejishuxueyuan", pyi: "rzzyjsxy", url: "https://www.rzvtc.cn/", location: "骞抽《灞卞競", type: "涓撶" },
        { id: 149, name: "鏋楀窞寤虹瓚鑱屼笟鎶€鏈闄?, py: "linzhoujianzhuzhiyejishuxueyuan", pyi: "lzjzzyjsxy", url: "https://lcat.edu.cn/", location: "瀹夐槼甯?, type: "涓撶" },
        { id: 150, name: "閮戝窞鐢靛瓙鍟嗗姟鑱屼笟瀛﹂櫌", py: "zhengzhoudianzishangwuzhiyexueyuan", pyi: "zzdzswzyxy", url: "https://www.zzdsxy.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 151, name: "閮戝窞杞ㄩ亾宸ョ▼鑱屼笟瀛﹂櫌", py: "zhengzhouguidaogongchengzhiyexueyuan", pyi: "zzgdgczyxy", url: "https://www.zzure.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 152, name: "閮戝窞浣撹偛鑱屼笟瀛﹂櫌", py: "zhengzhoutiyuzhiyexueyuan", pyi: "zztyzyxy", url: "https://www.zhengzhoutiyuan.com/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 153, name: "娲涢槼鏂囧寲鏃呮父鑱屼笟瀛﹂櫌", py: "luoyangwenhual眉youzhiyexueyuan", pyi: "lywhlyzyxy", url: "https://www.lyvcct.cn/", location: "娲涢槼甯?, type: "涓撶" },
        { id: 154, name: "鍛ㄥ彛鏂囩悊鑱屼笟瀛﹂櫌", py: "zhoukouwenlizhiyexueyuan", pyi: "zkwlzyxy", url: "https://www.zkwl.edu.cn/", location: "鍛ㄥ彛甯?, type: "涓撶" },
        { id: 155, name: "淇￠槼鑹烘湳鑱屼笟瀛﹂櫌", py: "xinyangyishuzhiyexueyuan", pyi: "xyyszyxy", url: "https://www.xyvca.edu.cn/", location: "淇￠槼甯?, type: "涓撶" },
        { id: 156, name: "閮戝窞鍩庡缓鑱屼笟瀛﹂櫌", py: "zhengzhouchengjianzhiyexueyuan", pyi: "zzcjzyxy", url: "https://www.zzucvc.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 157, name: "閮戝窞鍖昏嵂鍋ュ悍鑱屼笟瀛﹂櫌", py: "zhengzhouyiyaojiankangzhiyexueyuan", pyi: "zzyyjkzyxy", url: "https://www.zzyyzy.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 158, name: "骞抽《灞辫亴涓氭妧鏈闄?, py: "pingdingshanzhiyejishuxueyuan", pyi: "pdszyjsxy", url: "https://www.pdszy.edu.cn/", location: "骞抽《灞卞競", type: "涓撶" },
        { id: 159, name: "鍗楅槼宸ヨ壓缇庢湳鑱屼笟瀛﹂櫌", py: "nanyanggongyimeishuzhiyexueyuan", pyi: "nygymszyxy", url: "https://www.nygymy.com/", location: "鍗楅槼甯?, type: "涓撶" },
        { id: 160, name: "婵槼绉戞妧鑱屼笟瀛﹂櫌", py: "puyangkejizhiyexueyuan", pyi: "pykjzyxy", url: "https://www.pykjzyxy.com/index.html", location: "婵槼甯?, type: "涓撶" },
        { id: 161, name: "鍟嗕笜骞煎効甯堣寖楂樼瓑涓撶瀛︽牎", py: "shangqiuyouershifangaodengzhuankexuexiao", pyi: "sqyesfgdzkxx", url: "https://www.sqyz.edu.cn/", location: "鍟嗕笜甯?, type: "涓撶" },
        { id: 162, name: "鍛ㄥ彛鐞嗗伐鑱屼笟瀛﹂櫌", py: "zhoukouligongzhiyexueyuan", pyi: "zklgzyxy", url: "https://www.zkpvc.edu.cn/", location: "鍛ㄥ彛甯?, type: "涓撶" },
        { id: 163, name: "鐒︿綔鏂版潗鏂欒亴涓氬闄?, py: "jiaozuoxincailiaozhiyexueyuan", pyi: "jzxclzyxy", url: "https://jzxcl.edu.cn/", location: "鐒︿綔甯?, type: "涓撶" },
        { id: 164, name: "寮€灏佽亴涓氬闄?, py: "kaifengzhiyexueyuan", pyi: "kfzyxy", url: "https://www.kfvc.edu.cn/", location: "寮€灏佸競", type: "涓撶" },
        { id: 165, name: "娲涢槼鍟嗕笟鑱屼笟瀛﹂櫌", py: "luoyangshangyezhiyexueyuan", pyi: "lysyzyxy", url: "https://lyvcc.com/", location: "娲涢槼甯?, type: "涓撶" },
        { id: 166, name: "閮戝窞杞欢鑱屼笟鎶€鏈闄?, py: "zhengzhouruanjianzhiyejishuxueyuan", pyi: "zzrjzyjsxy", url: "https://www.zzsvtc.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 167, name: "閮戝窞鏅鸿兘绉戞妧鑱屼笟瀛﹂櫌", py: "zhengzhouzhinengkejizhiyexueyuan", pyi: "zzznkjzyxy", url: "https://www.zzcit.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 168, name: "閮戝窞椋熷搧宸ョ▼鑱屼笟瀛﹂櫌", py: "zhengzhoushipingongchengzhiyexueyuan", pyi: "zzspgczyxy", url: "https://www.zzfec.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 169, name: "閮戝窞姹借溅宸ョ▼鑱屼笟瀛﹂櫌", py: "zhengzhouqichegongchengzhiyexueyuan", pyi: "zzqcgczyxy", url: "https://www.zzvcae.edu.cn/", location: "閮戝窞甯?, type: "涓撶" },
        { id: 170, name: "椹婚┈搴楀啘涓氬伐绋嬭亴涓氬闄?, py: "zhumadiannongyegongchengzhiyexueyuan", pyi: "zmdnygczyxy", url: "https://www.zmdavc.edu.cn/", location: "椹婚┈搴楀競", type: "涓撶" },
        { id: 171, name: "淇￠槼绉戞妧鑱屼笟瀛﹂櫌", py: "xinyangkejizhiyexueyuan", pyi: "xykjzyxy", url: "https://www.xykj.edu.cn/", location: "淇￠槼甯?, type: "涓撶" },
        { id: 172, name: "淇￠槼宸ョ▼鑱屼笟瀛﹂櫌", py: "xinyanggongchengzhiyexueyuan", pyi: "xygczyxy", url: "https://www.xygczyxy.com/", location: "淇￠槼甯?, type: "涓撶" },
        { id: 173, name: "鍛ㄥ彛鍩庡競鑱屼笟瀛﹂櫌", py: "zhoukouchengshizhiyexueyuan", pyi: "zkcszyxy", url: "https://www.zkcszyxy.com/", location: "鍛ㄥ彛甯?, type: "涓撶" },
        { id: 174, name: "娌冲崡鏂颁埂宸ュ晢鑱屼笟瀛﹂櫌", py: "henanxinxianggongshangzhiyexueyuan", pyi: "hnxxgszyxy", url: "https://www.hnxxgs.edu.cn/", location: "鏂颁埂甯?, type: "涓撶" },
        { id: 175, name: "寮€灏佸伐绋嬭亴涓氬闄?, py: "kaifenggongchengzhiyexueyuan", pyi: "kfgczyxy", url: "https://www.kfevc.edu.cn/", location: "寮€灏佸競", type: "涓撶" },
        { id: 176, name: "寮€灏佹櫤鎱у仴搴疯亴涓氬闄?, py: "kaifengzhihuijiankangzhiyexueyuan", pyi: "kfzhjkzyxy", url: "https://www.kfzhjk.edu.cn/", location: "寮€灏佸競", type: "涓撶" },
        { id: 177, name: "鍛ㄥ彛鏅烘収鑳芥簮鑱屼笟瀛﹂櫌", py: "zhoukouzhihuinengyuanzhiyexueyuan", pyi: "zkzhnyzyxy", url: "https://www.zkzhny.edu.cn/", location: "鍛ㄥ彛甯?, type: "涓撶" },
        { id: 178, name: "骞抽《灞辩鎶€鑱屼笟瀛﹂櫌", py: "pingdingshankejizhiyexueyuan", pyi: "pdskjzyxy", url: "https://www.pdskj.edu.cn/", location: "骞抽《灞卞競", type: "涓撶" }
    ],
    sidebar: universitySidebar,
    filters: universityFilters
};

const govData = {
    items: [
        { id: 1, name: "娌冲崡鐪佹斂搴滈噰璐綉锛堢渷鏈骇锛?, py: "henanshengzhengfucaigouwang锛坰hengbenji锛?, pyi: "hnszfcgw锛坰bj锛?, url: "https://zfcg.henan.gov.cn/", location: "鐪佹湰绾?, type: "鐪佺骇", desc: "娌冲崡鐪佽储鏀垮巺涓诲姙" },
        { id: 2, name: "閮戝窞甯傛斂搴滈噰璐綉", py: "zhengzhoushizhengfucaigouwang", pyi: "zzszfcgw", url: "https://zhengzhou.zfcg.henan.gov.cn/", location: "閮戝窞甯?, type: "鍦板競绾?, desc: "閮戝窞甯傚垎绔? },
        { id: 3, name: "寮€灏佸競鏀垮簻閲囪喘缃?, py: "kaifengshizhengfucaigouwang", pyi: "kfszfcgw", url: "https://kaifeng.zfcg.henan.gov.cn/", location: "寮€灏佸競", type: "鍦板競绾?, desc: "寮€灏佸競鍒嗙珯" },
        { id: 4, name: "娲涢槼甯傛斂搴滈噰璐綉", py: "luoyangshizhengfucaigouwang", pyi: "lyszfcgw", url: "https://luoyang.zfcg.henan.gov.cn/", location: "娲涢槼甯?, type: "鍦板競绾?, desc: "娲涢槼甯傚垎绔? },
        { id: 5, name: "骞抽《灞卞競鏀垮簻閲囪喘缃?, py: "pingdingshanshizhengfucaigouwang", pyi: "pdsszfcgw", url: "https://pingdingshan.zfcg.henan.gov.cn/", location: "骞抽《灞卞競", type: "鍦板競绾?, desc: "骞抽《灞卞競鍒嗙珯" },
        { id: 6, name: "瀹夐槼甯傛斂搴滈噰璐綉", py: "anyangshizhengfucaigouwang", pyi: "ayszfcgw", url: "https://anyang.zfcg.henan.gov.cn/", location: "瀹夐槼甯?, type: "鍦板競绾?, desc: "瀹夐槼甯傚垎绔? },
        { id: 7, name: "楣ゅ甯傛斂搴滈噰璐綉", py: "hebishizhengfucaigouwang", pyi: "hbszfcgw", url: "https://hebi.zfcg.henan.gov.cn/", location: "楣ゅ甯?, type: "鍦板競绾?, desc: "楣ゅ甯傚垎绔? },
        { id: 8, name: "鏂颁埂甯傛斂搴滈噰璐綉", py: "xinxiangshizhengfucaigouwang", pyi: "xxszfcgw", url: "https://ccgp-henan.gov.cn/xinxiang", location: "鏂颁埂甯?, type: "鍦板競绾?, desc: "鏂颁埂甯傚垎绔? },
        { id: 9, name: "鐒︿綔甯傛斂搴滈噰璐綉", py: "jiaozuoshizhengfucaigouwang", pyi: "jzszfcgw", url: "https://jiaozuo.zfcg.henan.gov.cn/", location: "鐒︿綔甯?, type: "鍦板競绾?, desc: "鐒︿綔甯傚垎绔? },
        { id: 10, name: "婵槼甯傛斂搴滈噰璐綉", py: "puyangshizhengfucaigouwang", pyi: "pyszfcgw", url: "https://puyang.zfcg.henan.gov.cn/", location: "婵槼甯?, type: "鍦板競绾?, desc: "婵槼甯傚垎绔? },
        { id: 11, name: "璁告槍甯傛斂搴滈噰璐綉", py: "xuchangshizhengfucaigouwang", pyi: "xcszfcgw", url: "https://ccgp-henan.gov.cn/xuchang", location: "璁告槍甯?, type: "鍦板競绾?, desc: "璁告槍甯傚垎绔? },
        { id: 12, name: "婕渤甯傛斂搴滈噰璐綉", py: "luoheshizhengfucaigouwang", pyi: "lhszfcgw", url: "https://luohe.zfcg.henan.gov.cn/", location: "婕渤甯?, type: "鍦板競绾?, desc: "婕渤甯傚垎绔? },
        { id: 13, name: "涓夐棬宄″競鏀垮簻閲囪喘缃?, py: "sanmenxiashizhengfucaigouwang", pyi: "smxszfcgw", url: "https://sanmenxia.zfcg.henan.gov.cn/", location: "涓夐棬宄″競", type: "鍦板競绾?, desc: "涓夐棬宄″競鍒嗙珯" },
        { id: 14, name: "鍗楅槼甯傛斂搴滈噰璐綉", py: "nanyangshizhengfucaigouwang", pyi: "nyszfcgw", url: "https://nanyang.zfcg.henan.gov.cn/", location: "鍗楅槼甯?, type: "鍦板競绾?, desc: "鍗楅槼甯傚垎绔? },
        { id: 15, name: "鍟嗕笜甯傛斂搴滈噰璐綉", py: "shangqiushizhengfucaigouwang", pyi: "sqszfcgw", url: "https://shangqiu.zfcg.henan.gov.cn/", location: "鍟嗕笜甯?, type: "鍦板競绾?, desc: "鍟嗕笜甯傚垎绔? },
        { id: 16, name: "淇￠槼甯傛斂搴滈噰璐綉", py: "xinyangshizhengfucaigouwang", pyi: "xyszfcgw", url: "https://xinyang.zfcg.henan.gov.cn/", location: "淇￠槼甯?, type: "鍦板競绾?, desc: "淇￠槼甯傚垎绔? },
        { id: 17, name: "鍛ㄥ彛甯傛斂搴滈噰璐綉", py: "zhoukoushizhengfucaigouwang", pyi: "zkszfcgw", url: "https://zhoukou.zfcg.henan.gov.cn/", location: "鍛ㄥ彛甯?, type: "鍦板競绾?, desc: "鍛ㄥ彛甯傚垎绔? },
        { id: 18, name: "椹婚┈搴楀競鏀垮簻閲囪喘缃?, py: "zhumadianshizhengfucaigouwang", pyi: "zmdszfcgw", url: "https://ccgp-henan.gov.cn/zhumadian", location: "椹婚┈搴楀競", type: "鍦板競绾?, desc: "椹婚┈搴楀競鍒嗙珯" },
        { id: 19, name: "娴庢簮甯傛斂搴滈噰璐綉", py: "jiyuanshizhengfucaigouwang", pyi: "jyszfcgw", url: "https://ccgp-henan.gov.cn/jiyuan", location: "娴庢簮甯?, type: "鍦板競绾?, desc: "娴庢簮甯傚垎绔? }
    ],
    sidebar: govSidebar,
    filters: govFilters
};


